### ISSUE TITLE
Gutenberg compatibility: Add to defaults, show_in_rest -> true

### ISSUE THREAD

**Issue by claytoncollie** [johnbillion/extended-cpts#100]
for both custom post types and custom taxonomies, the argument `show_in_rest => true` needs to be added to their defaults to be compatible with Gutenberg.

**Comment by johnbillion** [comment]
I'm going to leave this as-is for now, mainly because there's a core ticket for the issue: https://core.trac.wordpress.org/ticket/42785

You can of course override the value of the argument in the `$args` array when registering your extended post type or taxonomy.
