### ISSUE TITLE
Dashboard Glance icon not matching 'menu_icon' argument

### ISSUE THREAD

**Issue by bigskillet** [johnbillion/extended-cpts#101]
Dashboard Glance icon shows a circle regardless of 'menu_icon' argument.

**Comment by johnbillion** [comment]
I've taken a look at this and the short answer is that it's not possible to set that icon to the same as the `menu_icon` argument. There's no support for it in WordPress core.

I'll see if I can come up with either a fix in this library or a fix for WordPress core.
