### ISSUE TITLE
Feature: Show which post template in admin column?

### ISSUE THREAD

**Issue by unijez** [johnbillion/extended-cpts#108]
If not possible, could this feature be added into the admin columns area?

Display which post template is being used for specific post?

**Comment by johnbillion** [comment]
This should be possible currently. The post template is stored in the `_wp_page_template` post meta field, and the available template names can be fetched using the `get_page_templates()` function.

You can package this up into a custom column. Here's some completely untested code:

```php
'my_column' => array(
	'title'    => 'Template',
	'function' => function() {
		$template = get_post_meta( get_the_ID(), '_wp_page_template', true );
		if ( $template ) {
			$templates = get_page_templates();
			echo $templates[ array_search( $template, $templates ) ];
		}
	},
),
```

**Comment by jezthomp** [comment]
Thank you for your reply and apologies for the delay, i tried your code above and got the following error...

`Notice: Undefined offset: 0 in /home/almond/public_html/wp-content/themes/Almond-Financial/inc/extended-cpts/services-cpt.php on line 28`

Line 28 is...

`echo $templates[ array_search( $template, $templates ) ];`

If i do a var_dump of `$templates` it just shows page templates, this is a column of a CPT with a CPT template?

Any ideas?

**Comment by johnbillion** [comment]
The code I posted wasn't tested. You just need to figure out how to pluck the template name out of the `get_page_templates()` array using the value from the `_wp_page_template` meta field.

**Comment by johnbillion** [comment]
Oh you need to pass some parameters to `get_page_templates()` for the post id and post type.
