### ISSUE TITLE
Wrap post thumbnail in post edit link

### ISSUE THREAD

**Issue by claytoncollie** [johnbillion/extended-cpts#112]
https://github.com/johnbillion/extended-cpts/blob/7110de2b959d218709a7e993706d53867b1663ec/src/class-extended-cpt-admin.php#L933

Can you please add another parameter to optionally wrap the featured image in the [post edit link](https://developer.wordpress.org/reference/functions/get_edit_post_link/)?

**Comment by johnbillion** [comment]
Doing some housekeeping. This could be useful but it's not a feature I'm planning on implementing myself. PRs welcome of course, but closing this off.
