### ISSUE TITLE
Taxonomy meta boxes and Gutenberg

### ISSUE THREAD

**Issue by herrschuessler** [johnbillion/extended-cpts#118]
As discussed in https://github.com/johnbillion/extended-cpts/issues/100, `show_in_rest` needs to be set to `true` for taxonomy meta boxes to show up.

When setting `'meta_box' => 'radio'` AND `'show_in_rest' => true` for a given taxonomy, the meta box will show up twice in the Gutenberg sidebar – once as radio box, once as default box.

**Comment by johnbillion** [comment]
Thanks for the report.

I've seen some weird Gutenberg behaviour when playing with parameters such as `show_in_rest` and `meta_box_cb`. It looks like Gutenberg doesn't respect the latter. I need to find some time to look into it properly.

**Comment by smeedijzer-internet** [comment]
Any update on this?

**Comment by mvdhoek1** [comment]
The PR from edwinsiebel works good, any update on this?

**Comment by johnbillion** [comment]
I've opened a PR for a better approach, which is to hide the meta box that the block editor provides and allow the meta box from Extended CPTs to work instead.

@mvdhoek1 @smeedijzer-internet @herrschuessler Would you like to test #140 and leave feedback on there?

**Comment by johnbillion** [comment]
Fixed in #140.
