### ISSUE TITLE
"Undefined property: stdClass::$filter_by" when adding admin filter for WP built in post_tag taxonomy

### ISSUE THREAD

**Issue by bonny** [johnbillion/extended-cpts#121]
When registered a custom post type I wanted a dropdown where I could select tags. I added it using this code:

```
'admin_filters' => [
    'tag' => [
        'title'    => __( 'All tags', 'iis' ),
        'taxonomy' => 'post_tag',
    ],
```

Which resulted in notice:

`Undefined property: stdClass::$filter_by`
in

`/vendor/johnbillion/extended-cpts/src/class-extended-cpt-admin.php:207`

**Comment by johnbillion** [comment]
Thanks for the report. I didn't consider the built-in Tag and Category taxonomies for this filter. They don't have the custom `filter_by` label defined.
