### ISSUE TITLE
Add support for "default" taxonomy term(s)

### ISSUE THREAD

**Issue by JacobDB** [johnbillion/extended-cpts#122]
Similar to how posts have a default "Uncategorized" category, it'd be awesome if we could set a default term for our custom taxonomies, which can't be deleted, and when unselected gets re-added.

**Comment by johnbillion** [comment]
Yeah I would definitely like to do this at some point.

Duplicate of #71.

**Comment by JacobDB** [comment]
Ah, thanks, I searched but didn't find that issue.
