### ISSUE TITLE
post_author not showing up when using Gutenberg

### ISSUE THREAD

**Issue by stuartshields** [johnbillion/extended-cpts#123]
So I had an issue earlier today with the `post_author` not saving the user id, after some tracking down I found that Gutenberg is the cause. Unless I am missing something in the below code:
```
	register_extended_post_type(
		'gallery',
		[
			'show_in_rest' => true,
			'rest_base'      => 'gallery',
		]
	);
```

**Comment by stuartshields** [comment]
Actually I believe this is related to Gutenberg itself and not this plugin.

**Comment by johnbillion** [comment]
You might need to add `author` to the post type support.
