### ISSUE TITLE
Registered Taxonomy Name

### ISSUE THREAD

**Issue by fabianwurk** [johnbillion/extended-cpts#129]
When I register a taxonomy called 'job-category' it adds '**s**' to menu name, so reads '**Job Categorys**', whereas, it should read '**Job Categories**'

Any idea to why this would be?

![Screenshot 2020-01-10 at 10 56 17](https://user-images.githubusercontent.com/18347097/72148127-f9aa7e80-3397-11ea-9938-ee25d4f9ac74.png)

Here is the code where it's being registered:

<img width="731" alt="Screenshot 2020-01-10 at 11 00 20" src="https://user-images.githubusercontent.com/18347097/72148335-6f164f00-3398-11ea-9ba1-c1ebd4a12ff2.png">

**Comment by johnbillion** [comment]
This is intentional, it's this automatic post type label generation.

Read the usage instructions for how to control this.

**Comment by fabianwurk** [comment]
Thanks John. 

Is it to do with the label attribute, and if yes, how do I change/add that on the function itself?

Sorry, I'm just not clear on this as new to this method of calling cpts/taxonomies.

**Comment by johnbillion** [comment]
It's the `$names` argument. Take a look at the usage section in the readme
and in the wiki where you'll find examples.

**Comment by fabianwurk** [comment]
Thanks, got it sorted now John using:

`add_action( 'init', function() {
	register_extended_post_type( 'story', [

		# Add the post type to the site's main RSS feed:
		'show_in_feed' => true,

		# Show all posts on the post type archive:
		'archive' => [
			'nopaging' => true,
		],

	], [

		# Override the base names used for labels:
		'singular' => 'Story',
		'plural'   => 'Stories',
		'slug'     => 'stories',

	] );

    register_extended_taxonomy( 'category', 'story', array(

        # Use radio buttons in the meta box for this taxonomy on the post editing screen:
        'meta_box' => 'radio',
    
        # Show this taxonomy in the 'At a Glance' dashboard widget:
        'dashboard_glance' => true,
    
        # Add a custom column to the admin screen:
        'admin_cols' => array(
            'updated' => array(
                'title'       => 'Updated',
                'meta_key'    => 'updated_date',
                'date_format' => 'd/m/Y'
            ),
        ),
    
    ), array(
    
        # Override the base names used for labels:
        'singular' => 'Category',
        'plural'   => 'Categories',
        'slug'     => 'categories'
    
    ) );
} );`
