### ISSUE TITLE
Taxonomy config not respected in quick edit

### ISSUE THREAD

**Issue by matbrady** [johnbillion/extended-cpts#133]
## Problem

Defining a custom Taxonomy with the below configuration is not respected by the Post list view 'quick edit' screen. My expectation is that in quick edit screen, radio buttons would also appear and only 1 term could be selected. 

```php
<?php

add_action('init', function () {

    register_extended_taxonomy('format', array('post', 'page'), array(

        'description' => 'The type of format',

        'meta_box' => 'radio',

        'exclusive' => true,

        'settings' => array(
            'show_in_nav_menus' => true,
            'show_ui' => true,
            'show_in_quick_edit' => true,
            'meta_box_cb' => false,
        ),

    ), array(

        # Override the base names used for labels:
        'singular' => 'Format',
        'plural' => 'Formats',
        'slug' => 'format',

    ));

});

```

#### Admin Page Edit Screen
Radio buttons appear as expected and only one can be selected. 

<img width="500" src="https://user-images.githubusercontent.com/1770862/77455722-a1005480-6dd0-11ea-991d-b428b07b822d.png" />

#### Admin Pages List View
Checkboxes appear and more then one term can be applied. After saving, in the edit screen above, the last term is chosen a being selected. However, there are actually still multiple terms applied to the Page.  
 
<img width="550" src="https://user-images.githubusercontent.com/1770862/77455892-d3aa4d00-6dd0-11ea-8d53-2e05546d9644.png" />

**Comment by johnbillion** [comment]
Thanks for the report! I must say that I almost always disable Quick Edit for custom post types, but  I will still look into what's involved in supporting this.

**Comment by johnbillion** [comment]
I just looked into this and it's not possible to target the `Walker` class that's used for this list of terms without affecting all other uses of `wp_terms_checklist()`, which isn't desirable because that would affect features such as filters on the front end.

As much as I'm tempted to put a patch into WordPress core that allows for this, I'm not too enthusiastic to be honest. I recommend disabling Quick Edit for this post type.
