### ISSUE TITLE
`allow_hierarchy` doesn't seem to be working

### ISSUE THREAD

**Issue by JacobDB** [johnbillion/extended-cpts#138]
My interpretation of this is that it's not supposed to allow nested categories, but when I enable this, I see no difference in behavior.

**Comment by johnbillion** [comment]
Yeah this is a parameter that I never fully implemented or documented. It's only used to control the `hierarchical` argument for the `rewrite` parameter when registering the taxonomy.

https://github.com/johnbillion/extended-cpts/blob/1d5581bac4297d2109b73dfdf5b7790381cf9c27/functions.php#L103

**Comment by JacobDB** [comment]
No chance this will ever be completed? In the last week I've worked on two projects where it'd be handy to use the hierarchical style of taxonomy without actually allowing hierarchy. Man, WordPress should really just have a setting like "behavior" or "style" in core that'd let you mix-and-match some features... sometimes I like the checkbox style for tags, and I'm sure some people would like the text input style for categories.

**Comment by johnbillion** [comment]
It's not something I plan on trying to implement in ExtendedCPTs, no, this would need to be fixed in WordPress core. No idea if there's a ticket for that though, I don't recall ever seeing one.
