### ISSUE TITLE
breaks with `wp media regenerate`

### ISSUE THREAD

**Issue by jrgd** [johnbillion/extended-cpts#139]
using Models for Roots/Sage9, https://github.com/soberwp/models 
with a custom taxonomy 'type', defined as per below:

```
{
  "type": "category",
  "name": "type",
  "links": [
    "post", "project"
  ],
  "labels": {
    "has_one": "Type of Project",
    "has_many": "Types of Project",
    "text_domain": "sage"
  }
}
```

using
`update_option( 'thumbnail_size_w', 200 );`
`update_option( 'thumbnail_size_h', 0 );`
in function.php/filter

and then running wp cli:`wp media regenerate`

it should process the images and resize them
however it returns the following error:

```
Fatal error: Taxonomy query var &quot;type&quot; is not allowed in
/---mypath---/site/vendor/johnbillion/extended-cpts/src/class-extended-taxonomy.php on line 235
```

removing extended-cpts with `composer remove johnbillion/extended-cpts`
allows to run `wp media regenerate` error-free as per below

```
➜  site git:(master) ✗ wp media regenerate
Do you really want to regenerate all images? [y/n] y
Found 8 images to regenerate.
1/8 Regenerated thumbnails for "---" (ID 38).
2/8 Regenerated thumbnails for "---" (ID 36).
3/8 Regenerated thumbnails for "---" (ID 34).
4/8 Regenerated thumbnails for "---" (ID 35).
5/8 Regenerated thumbnails for "---" (ID 33).
6/8 Regenerated thumbnails for "---" (ID 26).
7/8 Regenerated thumbnails for "---" (ID 27).
8/8 Regenerated thumbnails for "---" (ID 24).
Success: Regenerated 8 of 8 images.
```

**Comment by johnbillion** [comment]
`type` is a reserved term in WordPress: https://codex.wordpress.org/Reserved_Terms

You'll need to rename your taxonomy. This isn't anything specific to Extended CPTs.
