### ISSUE TITLE
Custom Sorting Field not working on Admin Column and no way to quick edit

### ISSUE THREAD

**Issue by fabianwurk** [johnbillion/extended-cpts#142]
I have a custom field for setting the 'Page Order' but it doesn't seem to be sorting correctly using:

```
		'admin_cols' => [
			'course_dept' => [
				'taxonomy' => 'team-department',
			],
			'role' => [
				'post_field' => 'role',
			],
			'page_order' => array(
				'post_field' => 'page_order',
				'default'  => 'DESC',
			),
		],
```
And I can't see a way to 'Quick Edit' this field? Is that possible?

Thanks

<img width="1364" alt="Screenshot 2020-07-14 at 18 27 19" src="https://user-images.githubusercontent.com/18347097/87457052-b14a7280-c5ff-11ea-9ca1-93562f14c666.png">

<img width="1373" alt="Screenshot 2020-07-14 at 18 26 17" src="https://user-images.githubusercontent.com/18347097/87457058-b3accc80-c5ff-11ea-9d20-2bde1b8dbbc5.png">

**Comment by johnbillion** [comment]
This is a name of a meta field key not a post field, so you need to use `meta_key` instead of `post_field`. The latter is for the built-in fields in the `wp_posts` database table.

Quick editing of custom fields isn't something that's natively supported by Extended CPTs as the requirements for custom fields can vary so much. Same reason it doesn't provide controls for custom fields on the post editing screen. You can use a custom field library such as ACF, FieldManager, or CMB2.

**Comment by fabianwurk** [comment]
So the field 'Page Order' is an ACF text field. And I need it to hold a numeric value so the titles can be ordered. 

So I've tried the following but it still won't order the fields?

```
			'page_order' => [
				'meta_key' => 'page_order',
				'default'    => 'DESC',
			],
```

<img width="1556" alt="Screenshot 2020-07-14 at 20 07 15" src="https://user-images.githubusercontent.com/18347097/87466129-ac8cbb00-c60d-11ea-9881-2a7079df1b85.png">

**Comment by johnbillion** [comment]
Is there a reason you're not using the built-in page ordering functionality in WordPress?

**Comment by damacs** [comment]
Just had to have the option to custom order the posts.

**Comment by johnbillion** [comment]
Regarding the ordering, this might be the same issue as #65 . The ordering in WordPress uses standard MySQL ordering which means, for text-based fields such as `meta_value`, this will sort alphabetically. `10` will come before `2`.

I want to add support for ordering numeric fields but I never got around to it.
