### ISSUE TITLE
Use add_action for action hooks, not add_filter

### ISSUE THREAD

**Issue by GaryJones** [johnbillion/extended-cpts#147]
- https://github.com/johnbillion/extended-cpts/blob/328930384b91ea57452200964106391e4c510acf/src/class-extended-cpt.php#L202
- https://github.com/johnbillion/extended-cpts/blob/f1c57cedbe88ebfd1d77d2ce8b2081174e091f02/src/class-extended-cpt-admin.php#L72

These two lines have got `add_filter( 'pre_get_posts', ... );` instead of `add_action()`.

While at the PHP level it makes no difference, we have a VIPCS sniff that specifically looks for filter hook callbacks to ensure that they have a returned value, and the incorrect function call is causing false positives.

There may be others as well, but these are two that stood out immediately.

**Comment by johnbillion** [comment]
Thanks for the report. Related: https://github.com/WordPress/WordPress-Coding-Standards/issues/713
