### ISSUE TITLE
Improve extending any previously registered post type

### ISSUE THREAD

**Issue by lkraav** [johnbillion/extended-cpts#15]
Related discussion on WP Slack, Apr 21st

My use case was: a plugin register a post type, where I'd like to quickly change labels, slugs etc on using extended-cpt, but keep whatever other functionality the plugin implements

register_post_type() can be called multiple times. Last one to arrive wins and will overwrite previous parameters.

https://github.com/johnbillion/extended-cpts/blob/master/extended-cpts.php#L690 checks for existing post types and if exists, falls back to only changing labels, when in fact it's possible to change whatever else you want as well.

In my particular case, the plugin sends its register_post_type $args through a filter, so I'm able to easily capture and store them, also doing stuff like array_replace_recursive() or whatever fits to merge with my own desired parameters.

get_post_type_object() returns an object, which to me looks needs conversion to array() for merging with whatever the user passes into register_extended_post_type().

My current recommendation is to drop `->extend()` and enhance merging algorithm of our incoming $args with the result value of get_post_type_object().

**Comment by johnbillion** [comment]
I'm not ignoring this issue by the way, Leho. I've been adding lots of test coverage in the `develop` branch. I'll check this out once I get to the `extend()` method! :+1:

**Comment by lkraav** [comment]
+1000

**Comment by lkraav** [comment]
Hey there. Looks like we're up to v3 already. Any fresh thoughts on the `extend()` front? Looking at the current `master` code, I think I still need my custom patch deployed on this project.

**Comment by johnbillion** [comment]
Doing some housekeeping. This is a feature that I rarely use myself, hence the lack of focus on it. I'm closing this off but as always a PR is welcome if you're interested in working on this.
