### ISSUE TITLE
Composer 2 throws error for dev dependency dealerdirect/phpcodesniffer-composer-installer

### ISSUE THREAD

**Issue by herrschuessler** [johnbillion/extended-cpts#150]
When installing via composer 2, I get the error 
```The "dealerdirect/phpcodesniffer-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.```

There seems to be an easy fix in https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/119 (installing the dev dependency via `composer require --dev dealerdirect/phpcodesniffer-composer-installer:"^0.7.0"`,  as apparently this dependency is indeed compatible with composer 2.

Just a minor issue, but probably easy to fix?

**Comment by johnbillion** [comment]
Thanks 👍
