### ISSUE TITLE
CPT taxonomies in admin_cols listed twice in dashboard

### ISSUE THREAD

**Issue by paulburgess** [johnbillion/extended-cpts#154]
Hi, I'm using a parent/child theme set up, CPTS are registered in the child theme.

```php
register_extended_post_type( 'music', array(
		'menu_icon' => 'dashicons-format-audio',
		'has_archive' => true,
		'taxonomies' => array('post_tag'),
		'show_in_rest' => false,
		 'admin_cols' => array(
				 'music_cat' => array(
					 'title'       => 'Catgory',
						 'taxonomy'    => 'music-category',
				 ),
				 'music_artist' => array(
					'title'       => 'Artist',
					'taxonomy'    => 'music-artist',
				),
		 ),
	),
	array(
   'singular' => 'Music',
   'plural'   => 'Music',
)
);
```

When the taxonomies are shown in the admin area, they are listed twice:

![CleanShot 2020-12-07 at 15 08 24](https://user-images.githubusercontent.com/504753/101367458-18620f80-389e-11eb-87a6-b836b17b444e.png)

Any idea what's up here?

Many thanks!

**Comment by johnbillion** [comment]
I can't immediately see a problem, but I will check it out.

**Comment by johnbillion** [comment]
@paulburgess I've been testing this and the only way I can reproduce it is if I register the post type twice, by calling `register_extended_post_type()` twice.

Can you check your code and see if this is the case please?

**Comment by paulburgess** [comment]
Ah yes John, that was it - thank you!

**Comment by johnbillion** [comment]
I suppose technically Extended CPTs should handle this gracefully, but I'm not sure how it might do that.

**Comment by johnbillion** [comment]
I'll close this for now as it's an edge case.
