### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by noplanman** [johnbillion/extended-cpts#157]
Is there anything blocking a bump to PHP 8?

Just wondering if it's just a matter of upping the requirement in `composer.json` or if there's a blocking factor somewhere.

**Comment by johnbillion** [comment]
Not as far as I know, but I haven't gotten around to testing properly. I'll add it to my to-do list. Thanks.

**Comment by johnbillion** [comment]
As expected, the library works fine with PHP 8 but the test tooling doesn't. I hacked the dependencies and ran the tests locally on PHP 8 and they all passed with no issues.

**Comment by johnbillion** [comment]
Released version 4.5.0 with updated PHP dependency in composer.json.
