### ISSUE TITLE
Consider using a different method to check a date/time type value

### ISSUE THREAD

**Issue by robert-h-at-cp** [johnbillion/extended-cpts#190]
The code [here](https://github.com/johnbillion/extended-cpts/blob/develop/src/PostTypeAdmin.php#L992) uses the function `strtotime()` to determine whether the string value is a date/time-ish string. However, the `strtotime()` function is super liberal and, for example, sometime mistake a timestamp string for a valid date/time string but would parse it into a wrong date/time object. See more details [here](https://github.com/php/doc-en/issues/1343)

Plz consider improving it by possibly using a different method.

**Comment by johnbillion** [comment]
Do you have an example of where this can get the date wrong? This handling was recently changed in version 5.0.0 in #187.

**Comment by robert-h-at-cp** [comment]
Oh. Thx! Didn't notice that it has already been patched. Will try the update. Closing the issue for now.
