### ISSUE TITLE
ACF date field not formatting correctly in admin column

### ISSUE THREAD

**Issue by paulburgess** [johnbillion/extended-cpts#206]
Hi, I have an ACF date field being displayed in an admin column like so:

`'event_start_date' => array(
			'title'       => 'Start date',
			'meta_key'    => 'event_start_date',
			'date_format' => 'd/m/Y'
		),`

That code formats the date like so:

<img width="139" alt="Screenshot-l2Q126KD@2x" src="https://user-images.githubusercontent.com/504753/183312723-00399e8b-e5fd-48e5-ad8f-fea127c28fb8.png">

If I remove the formatting, it displays the correct date, just in the more raw format:

<img width="145" alt="Screenshot-sRgspGTX@2x" src="https://user-images.githubusercontent.com/504753/183312720-ef7a3cf2-1c94-402b-b3fd-836940843229.png">

Oddly this same code and formatting works fine on another project which is using an older version of extended CPTs

Any idea what is going on here?

Many thanks!

**Comment by johnbillion** [comment]
What format is the `event_start_date` field stored in?

**Comment by paulburgess** [comment]
Hi, the format in the screenshot: YYYYMMDD

**Comment by paulburgess** [comment]
Oddly, it works fine in another project, and if I copy that older extended-cpts folder over to this one with the issue, it all works fine.

Where can I find the version number in the readme or license?

**Comment by johnbillion** [comment]
The version is in the extended-cpts.php file in the `@version` tag

**Comment by johnbillion** [comment]
#187 was a recent change to this handling

**Comment by paulburgess** [comment]
Thanks John, the version I was using 4.4.1 - where it works fine. I'm sorry, what do I need to alter to get the date formatting working again? I'm not sure what I'm looking for here: https://github.com/johnbillion/extended-cpts/pull/187

**Comment by paulburgess** [comment]
I have resolved this by moving away from ACF's date format of just YYYYMMDD, to use a Date / Time picker which saves the date in a timestamp format and works correctly with the latest Extended CPT date formatting.

It seems ACF use this format so they can support old versions of WP.

There are also ways of saving ACF date fields in the timestamp format via filters, but the date / time picker was my fix for this.

Thanks John!

**Comment by johnbillion** [comment]
Thanks for the update Paul. It's difficult to handle every possible date format, and seeing as a timestamp is a more portable format I think you made the best decision.
