### ISSUE TITLE
posts_per_page parameters

### ISSUE THREAD

**Issue by lumpysimon** [johnbillion/extended-cpts#21]
Would you be up for adding a parameter that would set the default number of posts displayed per page for that CPT? Even better would be one parameter for the front-end and one for the back-end.

Something like:

``` php
register_extended_post_type(
    'event',
    array(
        'public'               => true,
        'posts_per_page'       => 20,
        'admin_posts_per_page' => 50
        )
    );
```

Happy to submit a pull request if you like the idea.

**Comment by johnbillion** [comment]
You can do this currently for the front end with the `archive` parameter. It accepts any public or private query variables.

```php
register_extended_post_type( 'event', array(
    'archive' => array(
        'posts_per_page' => 20
    )
);
```

There's nothing for this in the admin area though. Definitely up for introducing a new parameter for that.

**Comment by lumpysimon** [comment]
Aha, that's very nifty - I hadn't noticed that you could pass in an array of arguments to the `archive` parameter.
