### ISSUE TITLE
Conflict with Permitpress Pro, proposed solution

### ISSUE THREAD

**Issue by JacobDB** [johnbillion/extended-cpts#211]
I was just setting up "Permitpress Pro" for a client, and saw that the dashboard errors out when this plugin is enabled in conjunction with extended-cpts. It's due to `src/PostTypeAdmin.php` at line 618, requiring the type `array`. With Permitpress Pro enabled, this value is being passed as `null`. To fix this, simply adding a `?` before the typecasting will allow for a null value, like so..

```php
	public function glance_items( ?array $items ): array {
```

I made this change locally and the dashboard started working again. It'd be great if we could get this in an official release.

**Comment by johnbillion** [comment]
Thanks for the report. You'll need to report this to Permitpress because null is not an accepted type for the `dashboard_glance_items` filter. See https://developer.wordpress.org/reference/hooks/dashboard_glance_items/
