### ISSUE TITLE
Package License "GPL-2.0+" is a deprecated

### ISSUE THREAD

**Issue by chrillep** [johnbillion/extended-cpts#212]
just a friendly notice :)
```sh
johnbillion/extended-cpts is valid, but with a few warnings
# General warnings
- License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0-or-later" instead
```

refs
* https://getcomposer.org/doc/04-schema.md#license
* https://spdx.org/licenses/
* https://spdx.org/licenses/GPL-2.0+.html
* https://spdx.org/licenses/GPL-2.0-or-later.html

**Comment by johnbillion** [comment]
Thanks!
