### ISSUE TITLE
P2P admin column error

### ISSUE THREAD

**Issue by m-e-h** [johnbillion/extended-cpts#23]
In the admin column, the following error is displayed instead of my connected 'department' post-type.
`
Warning: Invalid argument supplied for foreach() in extended-cpts.php on line 1865
`
I'm doing just the basic registering from the examples for both the `extended-post-type` and the `p2p connection`. The front-end display of the connection is working fine..

**Comment by johnbillion** [comment]
Confirmed. I'll take a look. Thanks for the report!

**Comment by johnbillion** [comment]
Weirdly, this has started working again in WordPress 4.4 beta. :confused:

**Comment by m-e-h** [comment]
:alien: Cool. I'll give it a try next week.

**Comment by edwinsiebel** [comment]
I did a [pull request](https://github.com/johnbillion/extended-cpts/pull/32) for this issue.
It works on my setup, however I don't know if my solution is solid (enough).
