### ISSUE TITLE
Search for CPT created using extend-cpts 

### ISSUE THREAD

**Issue by lmartins** [johnbillion/extended-cpts#24]
Im seeing a problem in my Dashboard, where a CPT created using this library never returns any results in the posts list, no matter whatever I search for in the search input.

The post type i've created is called "Docs" and can be seen in this screenshot (sorry, the contents on the list are in Portuguese but I think you get the ideia);
![screenshot 2015-07-29 16 26 08](https://cloud.githubusercontent.com/assets/151981/8961687/867b0226-360e-11e5-84d3-48b0aafe9c8a.png)

It was created with the following code:
```php
        register_extended_post_type( 'doc', array(
            'menu_icon' => 'dashicons-welcome-learn-more',
            'taxonomies' => array('post_tag'),

            # Add some custom columns to the admin screen:
            'admin_cols' => array(
                'topic' => array(
                    'taxonomy' => 'topic'
                )
            ),

            # Add a dropdown filter to the admin screen:
            'admin_filters' => array(
                'topic' => array(
                    'taxonomy' => 'topic'
                )
            )
        ) );
```

Considering the first post in the list, with the title "Formatação de textos", if I search for "textos" i get no results:
![screenshot 2015-07-29 16 27 51](https://cloud.githubusercontent.com/assets/151981/8961727/c29983f4-360e-11e5-99c8-fbdf439ab6ec.png)

This CPT also has a custom taxonomy "Topics" which I created using your library https://github.com/johnbillion/extended-taxos 

This taxonomy can be seen as the second column in the list. I used extended-cpts to add that column and the respective filter above, but if I try to filter de list for the topic "Escrever e Editar" which is assigned to several posts, including that first one given as an example, I still get no results:
![screenshot 2015-07-29 16 32 18](https://cloud.githubusercontent.com/assets/151981/8961830/6601eaae-360f-11e5-9818-a3ed9d493b09.png)

But if instead of using the select box above the list, I filter for that taxonomy term by pressing one of its occurrences in the list, I do get the expected behaviour:
![screenshot 2015-07-29 16 33 34](https://cloud.githubusercontent.com/assets/151981/8961867/917e7530-360f-11e5-8681-c6cfcfadfa70.png)

Have you seen this problem before, anything I am missing?
Thanks again.

**Comment by johnbillion** [comment]
Thanks for the detailed bug report, Luis!

I can't reproduce this on my development site with that post type and taxonomy registered. It could be that something else on your site is interfering with the search query.

 * Does searching work as expected on the front end?
 * Does searching other post types in the admin area work as expected?
 * Can you try disabling your other plugins one by one (and switching to a default theme) to see if the problem goes away?

**Comment by lmartins** [comment]
Let me run some tests to confirm the scenarios you are suggesting. I'll report back here once I get to any conclusion.

Many thanks for the library and all the help John, much appreciated.

**Comment by lmartins** [comment]
On a different site it works as expected. That confirms what you said about its probably something on my theme. I'll close this for now, will reopen if I get to different conclusion.

Thanks again for your support John.

**Comment by johnbillion** [comment]
Thanks for letting me know
