### ISSUE TITLE
Setting custom key value options for admin_filters doesn't work as intended

### ISSUE THREAD

**Issue by zachwills** [johnbillion/extended-cpts#28]
When I tried setting custom options for an admin filter, instead of using the key value for the `value` and the value for the label it used the label for both. So in the following example:

``` php
'admin_filters' => array(
	'sticky' => array(
		'title' => __( 'View Sticky' ),
		'meta_key' => Loader::META_PREFIX . 'sticky',
		'options'  => array(
			'on' => __( 'Sticky' ),
		),
	),
),
```

the output option was be `<option value="Sticky">Sticky</option>` when it should have been `<option value="on">Sticky</option>`.

If I get a chance I'll find the cause and submit a PR- in the meantime I wanted to report this issue so it was tracked.

**Comment by johnbillion** [comment]
Thanks! The problem lies in the `<select>` element generation in the `filters()` method.
