### ISSUE TITLE
Custom Menus Break In WordPress 4.4

### ISSUE THREAD

**Issue by jezthomp** [johnbillion/extended-cpts#33]
Custom menus no longer work when using the extended-cpts with WordPress 4.4

Registering is fine, once you add an actual new post within the custom post then the appearance > custom menus page basically doesn’t work, you can not add menu or even see the menus.

Delete the post you’ve created, empty the bin and the menus page come back in.

Happened since 4.4 was released.

**Comment by johnbillion** [comment]
Thanks, I've noticed this too. WordPress 4.4 supports post type archives in menus, so I can remove this functionality from ExtCPTs and it should fix this. I'll get an update out in the next few days.

**Comment by lmartins** [comment]
Was about to report what I believe is the same issue.
The error im getting is:
```
PHP Catchable fatal error:  Argument 3 passed to Extended_CPT_Admin::nav_menu_items() must be of the type array, object given in /Users/luismartins/Sites/webipack.dev/wp-content/themes/baseline/lib/extended-cpts/extended-cpts.php on line 1927
```

**Comment by johnbillion** [comment]
@lmartins Thanks! This will be fixed at the same time.

**Comment by JiveDig** [comment]
Was just troubleshooting broken menus and realized it was related to this plugin/class. Glad to see the active support. Thanks!
