### ISSUE TITLE
Menu Position

### ISSUE THREAD

**Issue by jawittdesigns** [johnbillion/extended-cpts#37]
Can you leave the menu position to the default NULL? I'm running into issues with the post types being overwritten by plugins.

My thinking is, it would be better to leave 'menu_position' to the default and let the developer choose if to specify the position to avoid conflicts with plugins.

Actually, it might be good to leave all the register_post_type() arguments to the defaults. Except public, having the default as false doesn't make sense. 

It just seems unnecessary to have to add extra code just to set the defaults back up.

**Comment by johnbillion** [comment]
Can you let me know how there is a conflict with other plugins? If two plugins register a menu in the same position, the latter ought to get bumped.

I won't be changing the defaults.

**Comment by jawittdesigns** [comment]
Well, you answered your own question. 

OK, whatevs.
