### ISSUE TITLE
link -> edit causes error

### ISSUE THREAD

**Issue by mmjaeger** [johnbillion/extended-cpts#40]
I started playing around with your script found on github and I’m running into the issue below when adding the following:

'category' => array(
	            'title'       => 'Categories',
	            'taxonomy'    => 'knowledge_category',
	            'link'			=> 'edit'
	        ),

link => edit causes the issue when I click on a category in the admin list or if you open categories

Am I missing something here or what could be the issue?

Thanks

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 856

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 857

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 858

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 859

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 860

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 861

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 856

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 857

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 858

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 859

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 860

Warning: sprintf(): Too few arguments in /Users/Marco/Sites/cms/wp-zementis/wp-content/themes/genesis-zementis/lib/extended-taxs.php on line 861

**Comment by johnbillion** [comment]
Thanks for the report. This is actually a bug in Extended Taxos, not Extended CPTs. See https://github.com/johnbillion/extended-taxos/issues/21
