### ISSUE TITLE
Format numbers in Dashboard columns and keep sorting

### ISSUE THREAD

**Issue by SiamKreative** [johnbillion/extended-cpts#45]
Hi John,

I'm stuck on something that might seem a bit ridiculous. How to format numbers in the columns without removing the sorting feature? For instance, I want to format the price properly (add currency and comma) but let ability to sort by price.

![screenshot-realestate dev 2016-05-02 16-30-00](https://cloud.githubusercontent.com/assets/1778633/14951446/28376772-1083-11e6-9912-2c91b737039a.png)

If I use a custom function, then the sorting is disabled:

```php
<?php
# Add some custom columns to the admin screen:
'admin_cols'    => array(
	'price'          => array(
		'title'    => 'Price',
		'meta_key' => 'price',
	),
	'price_psf'      => array(
		'title'    => 'PSF Price',
		'function' => function () {
			$price = intval(get_field('price'));
			$sqm   = intval(get_field('sqm'));
			if ($price && $sqm) {
				$price_psf = round($price / $sqm, 1);
				echo $price_psf . " Baht / sqm";
			} else {
				echo 'NA';
			}
		},
	),
),
```

I'd be grateful if you could help me find a solution.

Thanks

**Comment by johnbillion** [comment]
Hi Julien,

I've not tested it, but you might be able to supply the `'meta_key' => 'price'` argument to the column in addition to the `function => ...' argument, which will enabled the column to be sorted by the `price` meta field.

If that's not what you want, then there's no functionality within Extended CPTs which will allow you to sort a column based on a custom callback function.
