### ISSUE TITLE
Parse error: syntax error, unexpected '[', expecting ')' 

### ISSUE THREAD

**Issue by jezthomp** [johnbillion/extended-cpts#46]
I’m getting the following error, the hosting rubbish?

`Parse error: syntax error, unexpected '[', expecting ')' in /home/modxsaq/public_html/new/wp-content/themes/site-theme/inc/cp/extended-cpts.php on line 1271`

**Comment by johnbillion** [comment]
Yes, this means your hosting is using a very old version of PHP. Extended CPTs [requires PHP 5.4](https://github.com/johnbillion/extended-cpts#minimum-requirements).

You should ask your host to upgrade PHP!
