### ISSUE TITLE
Support for custom rewrite tags

### ISSUE THREAD

**Issue by JiveDig** [johnbillion/extended-cpts#50]
I'm banging my head against a wall with custom rewrite tags. In my current situation i'm trying to add a connected CPT slug as a base in another CPT's permalink.

I'm wondering if it's somehow feasible to add a custom rewrite tag to the rewrite permastruct.
Something like:
`'rewrite' => array(
    'permastruct' => '/%connected_post_slug%/%cpt_slug%',
),`

Then just use an additional post_type_link filter to define it. I've been trying this for 2 days now and only sometimes does it partially work, then continues to break for unknown (to me) reasons.

**Comment by johnbillion** [comment]
Off the top of my head I'm not sure if that will work reliably. Have you tried adding a prefix? For example `/hello/%connected_post_slug%/%cpt_slug%`.

What does your code in the `post_type_link` filter look like?

**Comment by JiveDig** [comment]
A prefix huh? It actually does work when i add %post_id% (or something static). Is that proving my lack of understanding about the rewrite API? Not sure why it needs the prefix.

My filter was different, and is now based off yours, but very similar either way.
`	/**
	 * Filter the post type permalink in order to populate its rewrite tags.
	 * Borrowed from Extended CPTs
	 *
	 * @see    https://github.com/johnbillion/extended-cpts/blob/master/extended-cpts.php#L608
	 *
	 * @since  TBD
	 *
	 * @param  string   $post_link  The post's permalink.
	 * @param  WP_Post  $post       The post in question.
	 * @param  bool     $leavename  Whether to keep the post name.
	 * @param  bool     $sample     Is it a sample permalink.
	 *
	 * @return string             The post's permalink.
	 */
	public function post_type_link( $post_link, WP_Post $post, $leavename ) {
		# If it's not our post type, bail out:
		if ( self::STEP != $post->post_type ) {
			return $post_link;
		}

		$replacements = array();

		if ( false !== strpos( $post_link, '%wampum_step_program%' ) ) {
			// This method gets the slug of the connected post
			$replacements['%wampum_step_program%'] = $this->get_step_program_slug($post);
		}

		$post_link = str_replace( array_keys( $replacements ), $replacements, $post_link );
		return $post_link;
	}`
