### ISSUE TITLE
Option to control admin columns order?

### ISSUE THREAD

**Issue by lmartins** [johnbillion/extended-cpts#54]
Hi,

Im extending an existing post type to add a few admin columns. By default it seems that the columns added by extended-cpts are placed first in the post list:
![screenshot 2016-08-12 11 34 14](https://cloud.githubusercontent.com/assets/151981/17619956/ba3bf88e-6080-11e6-885c-5e91ac1de3f4.png)

The brand column was created with the library. Do we have an option to control how the added columns are displayed on the list?

**Comment by johnbillion** [comment]
It's a bit of a difficult thing to deal with, but yes you can achieve this by specifying the IDs of the other columns in your `admin_cols` array. For example:
```php
'admin_cols' => array
