### ISSUE TITLE
Expose the CPT objects

### ISSUE THREAD

**Issue by shadyvb** [johnbillion/extended-cpts#56]
There is times where we'd need to remove/add/alter some hooks, so far I've not found a way to catch a CPT object unless I save the reference somewhere on the time of registration, which isn't always the best way of doing that in a pluggable env.

Something along these lines would be useful:

```
add_filter( 'ext-cpts/{$cpt}/instance', function() use ( $instance ) { return $instance; } );
```

**Comment by johnbillion** [comment]
I think I'll do this as an action.

```php
do_action( "ext-cpts/{$post_type}/instance", Extended_CPT $this );
```

Does that work for your use case?

**Comment by shadyvb** [comment]
I believe it might, can't really remember the exact case, but this should probably do it.
