### ISSUE TITLE
Post updated messages to be omitted if default labels are provided

### ISSUE THREAD

**Issue by Quaked** [johnbillion/extended-cpts#59]
Hi,

So I've manually added labels as per 'standard' register_post_type() args, so they're in Swedish and all fine. However, since "post_updated_messages" and "bulk_post_updated_messages" are hard-coded they do not translate well at all. The default behavior of WP would manage this if the set language of WP is sv_SE, the plugin does not.

As I see it, if one has provided labels manually AND WP language isn't English, don't add_filters() on line https://github.com/johnbillion/extended-cpts/blob/master/extended-cpts.php#L874 and https://github.com/johnbillion/extended-cpts/blob/master/extended-cpts.php#L875

Right now I've filtered them and added "my own" even though if they were never added I wouldn't have needed to. Se essentially I go from Swedish to English back to Swedish again which is kind of weird. I understand it's due to the 'ease' of just doing register_extended_post_type( 'article' ) and the plugin will magically do everything, but in this case magic isn't wanted.

Maybe check WP_LANG/get_locale() or similar as well as if default args ARE passed, skip applying the filters? Just a thought.

```if( substr( get_locale(), 0, 3 ) == 'en_' && !$this->args['labels']['singular_name'] )```

or simply add a new argument which is true by default but when false it won't apply the filters?

Edit: seems like this might need more work with internationalization as default WP will basically assume any CPT is a 'post' so Post updated vs. Article updated vs. custom filtered Artikel uppdaterad.

I'll leave my filters in but I guess this is 'food for thought'!

**Comment by johnbillion** [comment]
Thanks for the message.

You're right that Extended CPTs does effectively overwrite the translated version of the `Post` post type messages with its non-translated messages, but as you also noted in your edit the default messages are for the `Post` post type.

The label and message generation is really a utility for those people who need to create post types but don't need to translate them. If you do need translations then you'll need to do as you're doing and provide the full `labels` array, but also specify the updated messages which is a bit more of a faff.
