### ISSUE TITLE
replace Auto Draft when cpts doesn't support title

### ISSUE THREAD

**Issue by sandrodz** [johnbillion/extended-cpts#60]
Is there a way to modify `Auto Draft` using this plugin? At least put there a post id ?
<img width="349" alt="screen shot 2017-06-07 at 10 01 47 am" src="https://user-images.githubusercontent.com/8479569/26864283-58c56a3a-4b68-11e7-978f-d0016cda7da7.png">

my cpts doesn't support title.

**Comment by johnbillion** [comment]
I've seen this before too. There are actually several bugs in WordPress core with regard to post types that don't support the title.

I don't think it's within the scope of ExtCPTs to fix this, it ought to be addressed in WordPress core really. Showing the post ID is an option, but isn't ideal.

I wonder if showing `{post_type}: {ID}` (eg. `Gift Order: 123`) for each post would be better.

Related core bugs:

* https://core.trac.wordpress.org/ticket/40608
* https://core.trac.wordpress.org/ticket/29320
