### ISSUE TITLE
admin_cols meta_key modify displayed value

### ISSUE THREAD

**Issue by sandrodz** [johnbillion/extended-cpts#61]
<img width="469" alt="screen shot 2017-06-07 at 10 03 27 am" src="https://user-images.githubusercontent.com/8479569/26864327-93389228-4b68-11e7-8aa7-96096489ce30.png">

<img width="1049" alt="screen shot 2017-06-07 at 10 04 20 am" src="https://user-images.githubusercontent.com/8479569/26864355-b90e8066-4b68-11e7-9fb8-8bdc281db195.png">

I want following logic:
a. if status = 0 display `created`
b. if status = 1 display `claimed`

I want to use callback function as stated in docs, but Wiki says that I need to use global $post here, seems excessive to do all the postmeta query manually. Is there a better way?

**Comment by johnbillion** [comment]
You can use `get_post_meta( get_the_ID(), 'gift_order_status', true )` from within your call back function to get the meta value. This won't cause any extra database queries because it gets pre-cached by WordPress when the posts are fetched.

**Comment by sandrodz** [comment]
No need. I did following:

<img width="432" alt="screen shot 2017-06-07 at 2 44 19 pm" src="https://user-images.githubusercontent.com/8479569/26874762-de1231c4-4b8f-11e7-8a5f-14bbfcd34674.png">
