### ISSUE TITLE
Has archive forced

### ISSUE THREAD

**Issue by christianmagill** [johnbillion/extended-cpts#68]
Regardless of whether I set 'has_archive' to false or not, an archive is still created.

```
add_action('init', function(){
	register_extended_post_type( 'event',
		[
			'supports' => ['title', 'editor'],
			'public' => true,
			'show_in_admin_bar' => true,
			'show_in_menu' => true,
			'publicly_queryable' => true,
			'has_archive' => false,
			'archive' => false
		]
	);
});
```

**Comment by johnbillion** [comment]
Thanks for the report, but I can't reproduce this issue. Did you flush your permalink settings after changing the `has_archive` setting?

If you set it to `true`, flush your permalinks, then set it to `false` without flushing your permalinks, you will see an archive. This is a fundamental shortcoming in WordPress and not related to this library.
