### ISSUE TITLE
Select multiple

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/extended-cpts#69]
_From @SiamKreative on April 27, 2016 9:17_

Hi John,

Thanks for the great library, it's extremely useful for developers like me who mainly do front-end stuff.
#### Explanations

I would like to know if it's possible to somehow add the `multiple` attribute to the existing select dropdown. [It looks like](https://github.com/johnbillion/extended-taxos/blob/master/extended-taxos.php#L705-L721) you're using the [wp_dropdown_categories](https://codex.wordpress.org/Function_Reference/wp_dropdown_categories) function, but I see no option to turn it into a select multiple.
#### Why am I asking for this?

I prefer to use Select2 or Selectize.js rather the built-in default multiple checkbox thingy, mainly because I want it to be searchable.

![image](https://cloud.githubusercontent.com/assets/1778633/14847549/6b609922-0c93-11e6-9942-73ff39e47d98.png)

Cheers

_Copied from original issue: johnbillion/extended-taxos#23_

**Comment by johnbillion** [comment]
_From @SiamKreative on April 27, 2016 9:39_

I'm currently trying another approach using `simple` (the list of checkboxes): https://dl.dropboxusercontent.com/u/28858864/screencasts/filtering_wordpress_taxonomy_metabox.webm

In terms of UX, it's far from being ideal.

**Comment by johnbillion** [comment]
I did actually think about adding support for a Select2 dropdown, but the complication came from the fact that `wp_dropdown_categories()` doesn't support multiple selected values, so I would have to implement my own version of that function.

Unfortunately it's probably not something I'll have much time to look into for a while yet.

Related: https://core.trac.wordpress.org/ticket/31696

**Comment by johnbillion** [comment]
_From @SiamKreative on April 27, 2016 12:8_

_Thanks for the prompt reply John._

If I want to build the select multiple myself, should I re-use some code from the `simple` metabox? https://github.com/johnbillion/extended-taxos/blob/master/extended-taxos.php#L739-L780

And then add a new `case` to the `switch`?

**Comment by johnbillion** [comment]
_From @roborourke on May 31, 2017 14:39_

@SiamKreative why not just use the default non hierarchical meta box like tags? That has search and allows multiple items.

**Comment by SiamKreative** [comment]
At that time I wanted to have a select multiple that I could style however I wanted. That's not a big deal if we cannot @johnbillion
