### ISSUE TITLE
Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by melvinkoopmans** [johnbillion/extended-cpts#78]
When a query contains an array notated 'orderby', it will give an `Illegal offset type in isset or empty` warning.

For instance: 
```php
// ...
'orderby' => [
    'post_title' => 'ASC', 
    'post_date' => 'DESC'
],
// ...
```

Will give an `Illegal offset type in isset or empty` warning in `extended-cpts.php` on:

Line **437**:

```php
if ( ! isset( $sortables[ $vars['orderby'] ] ) ) {
    return array();
}
```

and line **486**:

```php
if ( ! isset( $sortables[ $vars['orderby'] ] ) ) {
    return array();
}
```

**Comment by johnbillion** [comment]
Thanks for the report!
