### ISSUE TITLE
Admin columns title move

### ISSUE THREAD

**Issue by dmpinder** [johnbillion/extended-cpts#79]
Hey John, I just come across a potential bug / something that isn't documented.

When defining `admin_cols`, it's mentioned in the docs that putting `'title'` in the array somewhere will move the title to that position. However this doesn't seem to work just by adding `'title'`. I have managed to get it working by including `'title'` with an array containing some values, e.g. just re-defining the column title. 

So in summary this doesn't move the title column:

```
'admin_cols' => array(
	'photo' => array(
		'title'       => 'Photo',
		'function' => function() {
			echo '<img src="'. get_field('photo') .'" width="40" height="40">';
		},
	),
	'title',
	'group' => array(
		'taxonomy' => 'group'
	),
),
```

But this does move it:

```
'admin_cols' => array(
	'photo' => array(
		'title'       => 'Photo',
		'function' => function() {
			echo '<img src="'. get_field('photo') .'" width="40" height="40">';
		},
	),
	'title' => array(
		'title' => 'Team Member'
	),
	'group' => array(
		'taxonomy' => 'group'
	),
),
```

It isn't really a huge problem, but if this is meant to work this way, then the Wiki needs updating to mention this.

Thanks!

**Comment by johnbillion** [comment]
Thanks for the report, this has definitely worked in the past. I'll take a look and see what's going on.

**Comment by johnbillion** [comment]
Doing some housecleaning. I think this is still an issue but I'm not too concerned about it, so closing this off.
