### ISSUE TITLE
Adding same taxonomy to multiple post types

### ISSUE THREAD

**Issue by kaisermann** [johnbillion/extended-cpts#80]
Is there a way to create a taxonomy with, let's say `register_extended_taxonomy` and use its return value as the parameter for `$post_type->add_taxonomy()`?

Thanks for the awesome lib!

**Comment by johnbillion** [comment]
`register_extended_taxonomy()` allows you to pass an array of post types:

```php
register_extended_taxonomy( 'foo', [ 'post', 'page', 'my_cpt' ] );
```

Also, the `$post_type->add_taxonomy()` method can be used to add an existing taxonomy to the post type (it first checks whether the taxonomy exists before trying to create it), so you can do something like this:

```php
register_extended_taxonomy( 'foo', 'post' );
```

Does that answer your question? As long as you register the post type(s) before the taxonomy you'll usually be able to do what you want to do.

**Comment by kaisermann** [comment]
Yeah it does! Thank you very much 😄
