### ISSUE TITLE
Trigger warning if permastruct doesn't contain a unique identifier

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/extended-cpts#90]
A permalink structure can be provided which doesn't contain a unique identifier. If this is the case, Extended CPTs should trigger a warning.

Example:

```php
add_action( 'init', function() {
	register_extended_post_type( 'foo', [
		'rewrite' => [
			'permastruct' => 'foo/bar',
		],
	] );
} );
```

AFAIK, `%postname%`, `%{post_type}%`, and `%post_id%` are the only unique identifiers, but I don't think `%post_id%` works for CPTs. Needs some testing.

**Comment by stuartshields** [comment]
@johnbillion So I ran into this issue on a project. It looks like when you use `%post_id%` it's missing the following rules (gallery is our CPT):

```
gallery/post-([^/]+)(?:/([0-9]+))?/?$    index.php?gallery=$matches[1]&page=$matches[2]
```

Using a plugin like hm-rewrite to add this rule in fixes the issue.
