### ISSUE TITLE
Quick Edit fields

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/extended-cpts#91]
It should be possible to add support for custom Quick Edit fields.

Ref: https://www.sitepoint.com/extend-the-quick-edit-actions-in-the-wordpress-dashboard/

**Comment by claytoncollie** [comment]
This would be great to integrate. On my CPT, person, I removed the default title field and replaced with multiple custom fields for first, middle, last name then, on save, create the title form those fields.  When using quick edit, the title fields are lost/overwritten. I'm having to disable quick edit for now which is not a huge deal. Just would a nice to have.
