### ISSUE TITLE
Add post type as class selector in At A Glance widget link

### ISSUE THREAD

**Issue by claytoncollie** [johnbillion/extended-cpts#97]
Dashboard glance items pull in menu icons via CSS.  Right now, the link being created does not have an identifier for me to target in my stylesheet.  It would be useful to add the post type name to this string on [line 464](https://github.com/johnbillion/extended-cpts/blob/master/src/class-extended-cpt-admin.php#L464)

`$text = '<a href="' . esc_url( $url ) . '" class="' . esc_attr( $this->cpt->post_type ) . '">' . esc_html( $num . ' ' . $text ) . '</a>';`

**Comment by johnbillion** [comment]
Related: #101
