### ISSUE TITLE
Custom Taxonomy url?

### ISSUE THREAD

**Issue by unijez** [johnbillion/extended-cpts#98]
How is the custom slug of a custom tax setup, the following doesn't work for me..

`register_extended_taxonomy( 'college-area', 'innovations', [
	'singular' => 'College',
	'plural'   => 'Colleges',
	'slug'     => 'university-college-area',
] );
`

**Comment by johnbillion** [comment]
What's the problem that you're seeing?

**Comment by unijez** [comment]
Sorry, i forgot to say!

Basically it doesn't effect the url of the custom tax archive page at all.

Its just `site.com/college-area/custom-tax-name` rather than `site.com/university-college-area/custom-tax-name`

Just wondered if i'm naming it wrong or if its even possible?

**Comment by johnbillion** [comment]
Apologies for only now getting back to you on this issue. In your example code, you're passing in the labels array as the third parameter of `register_extended_taxonomy()`, which is the `$args` parameter. This code works as expected for me:

```php
register_extended_taxonomy( 'college-area', 'innovations', [], [
	'singular' => 'College',
	'plural'   => 'Colleges',
	'slug'     => 'university-college-area',
] );
```
